# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
vector = np.zeros(10)
print (vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [ ]:
vector2 = np.arange(10,49)
result = np.vstack(vector2)
result

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48]])

4. Find the shape of previous array in question 3

In [ ]:
vector2.shape

(39,)

5. Print the type of the previous array in question 3

In [ ]:
vector2.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [ ]:
np.__version__
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/DELL/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:

7. Print the dimension of the array in question 3


In [ ]:
vector2.shape

(39,)

8. Create a boolean array with all the True values

In [ ]:
np.ones((2,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array




In [ ]:
two_dimentional = np.array([[2,3,4], [1,2,3]])
print (two_dimentional)

[[2 3 4]
 [1 2 3]]


10. Create a three dimensional array



In [ ]:
three_dimentional = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print (three_dimentional)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [ ]:
reverse = vector2[::-1]
print (reverse)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [ ]:
null_vector = np.zeros(10)
print (null_vector)
print ("update 5th value to 1")
null_vector[4] = 1
print (null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
update 5th value to 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [ ]:
three_matrix = np.arange(2,11).reshape(3,3)
print (three_matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [ ]:
arr = np.array([1.1,2.2,3.3,4.4])
float_datatype_convert = arr.astype (np.float)
print (float_datatype_convert)
float_datatype_convert.dtype

[1.1 2.2 3.3 4.4]


dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])




In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

print (arr1 * arr2)

[[ 0  8  3]
 [28 10 72]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]]) 
arr2 = np.array([[0,4,1],[7,2,12]])

comparing = arr1 = arr2
print (comparing)

[[ 0  4  1]
 [ 7  2 12]]


17. Extract all odd numbers from arr with values(0-9)

In [ ]:
odd_numbers = np.array(range (0,9))

print("odd number ", odd_numbers[odd_numbers%2==1])


odd number  [1 3 5 7]


18. Replace all odd numbers to -1 from previous array

In [ ]:
odd_numbers = np.array(range (0,9))

replace_oddnumbers = odd_numbers[odd_numbers%2==1]

odd_numbers[replace_oddnumbers] = -1

print ("the values with minus numbers ",odd_numbers)

the values with minus numbers  [ 0 -1  2 -1  4 -1  6 -1  8]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [ ]:
arr = np.arange(10)

arr[5:9] = 12
print (arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [ ]:
twod_array = np.ones((5,5))
print (twod_array)

print ("update border with 1 and 0 inside ")

twod_array[1:-1, 1:-1] = 0

print (twod_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
update border with 1 and 0 inside 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [ ]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

print (arr2d)

print ("replacing the value 5 to 12")
arr2d[1:2,1:2] = 12

print (arr2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
replacing the value 5 to 12
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print (arr3d)

print ( end = "\n ")
print ("after converting the values ")
print ( end = "\n ")

arr3d[:1, :1] = 64

print (arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

 after converting the values 

 [[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [ ]:
slice_twodimentional = np.arange(0,9).reshape(3,3)

print (slice_twodimentional)
slice_twodimentional[0,0:2+1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [ ]:
slice_twodimentional = np.arange(0,9).reshape(3,3)

slice_twodimentional[1,0:2+1]

array([3, 4, 5])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [ ]:
slice_twodimentional = np.arange(0,9).reshape(3,3)

print (slice_twodimentional)
print ("after slicing ")

slice_twodimentional[0:2,1:2+1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
after slicing 


array([[1, 2],
       [4, 5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
find_value = np.random.random((10,10))



min_value = find_value.min()
max_value = find_value.max()
print ("\n")
print ("the minimun value is :", min_value)
print ("the maximum value is :", max_value)




the minimun value is : 0.040578175579624065
the maximum value is : 0.9959951447957467


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

common_values = np.intersect1d(a,b)
print ("finding the common values are ", common_values)



finding the common values are  [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [ ]:
value1 = np.array([1,2,3, 2,3,4,3,4,5,6]) 
value2 = np.array([7,2,10,2,7,4,9,4,9,8])



common_values2 = np.where(value1 == value2)


common_values2




(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

i = names != "Will"
data [i]


array([[ 0.73566257, -2.16362322,  1.18285285,  0.51238661],
       [ 2.07797842, -1.4736535 ,  0.68617225, -0.47222413],
       [-1.0537429 ,  0.27542404, -0.27393494, -0.24454996],
       [-1.03329895, -0.51940359,  0.46823238, -1.70428056],
       [-0.6116205 ,  0.29385205, -0.01637398, -0.09114428]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

data [(names != "Joe") & (names != "Will") ]

array([[-0.01504943, -0.17142417, -0.71160224, -1.76957321],
       [ 0.65669555,  2.17809952,  1.16484769,  0.43695565]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [ ]:
import numpy as np

arr = np.arange(15, dtype = np.float64).reshape (5,3)
arr


array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [ ]:
x = np.arange(1,16+1, dtype=np.float64).reshape(2,2,4)

print (x)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [ ]:
x = np.arange(1,16+1).reshape(2,2,4)

print ("print the original array ")
print (x)

x[:,[0, 1]] = x[:,[1, 0]]
print("\nAfter swapping arrays:")
print(x)


print the original array 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

After swapping arrays:
[[[ 5  6  7  8]
  [ 1  2  3  4]]

 [[13 14 15 16]
  [ 9 10 11 12]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [ ]:
x = np.arange(10)
y = np.sqrt(x)
print ("\n the values after square root :")
print (y)
print ("\n after replacing the values less than 0.5 ")
print ("\n")
y[y<0.5 ] = 0

print (y)


 the values after square root :
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

 after replacing the values less than 0.5 


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [ ]:
x = np.random.random(12)
y = np.random.random(12)
z = np.maximum(x,y)

z

array([0.9180822 , 0.85686302, 0.53546214, 0.76116293, 0.61263504,
       0.30393066, 0.87874968, 0.43728183, 0.66117524, 0.62319631,
       0.83081038, 0.58128872])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

z = np.unique(names)
print (np.sort(z))



['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [ ]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

c = np.setdiff1d (a,b)
c


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [ ]:
import numpy 
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = numpy.array([[10,10,10]])

print (sampleArray)
sampleArray[:,2] = newColumn
print ("\n after inserting the new values at column two  ")
print (sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]

 after inserting the new values at column two  
[[34 43 10]
 [82 22 10]
 [53 94 10]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

z = np.dot(x,y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [ ]:
matrix = np.random.randn(20)

comulative_sum = np.cumsum(matrix)
comulative_sum

array([-1.63041313, -2.12586289, -1.55901383, -2.51465984, -4.76333305,
       -5.13609742, -5.00912374, -4.63971599, -3.34274138, -1.9270263 ,
       -0.56875975, -1.11810335, -1.35096172, -0.61068234, -1.25167347,
       -0.65514548, -0.30349087,  0.5863918 ,  3.24591179,  3.76331784])